# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 70af4b1442230d1dd8d67f927227e4fd67b1c487f71da5bd2aa4b331f25e239509032da8fedae178a6066de1594dab459ba2b1f0479968b53163b5060abed8b5

test:
  secret_key_base: 158e8fc9a824bd39bb60133b0a61e13878565cb261d98e48819c53f81497fb23a55a00fe3d7d8168385eec3578cc7e3a8097ef7f82647988435c1ec5b0888dea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
